# Site settings
title: Jaya Surya J
description: DevOps Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jaya Surya J
user_description: I'm a DevOps Engineer from Bangalore, always searching for the next challenge; no task is too scary nor too difficult. 
user_title: DevOps Engineer
email: jsurya1729@gmail.com
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: jayasuryaj
github_username:  SURYA-J
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

