version: '3'

services:
  jekyll:
    container_name: surya-j
    image: jekyll/jekyll
    command: jekyll serve --watch --force_polling --verbose --livereload --host 0.0.0.0
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
